<?php

declare(strict_types=1);

namespace Mazaya\License\Guard;

use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;
use Throwable;

/**
 * A digest of the licensing code as it was when the licence was issued.
 *
 * Folded into the configuration seal, so editing or deleting any part of this
 * package invalidates the licence rather than disabling it. That is the point:
 * a check that can be commented out is not a check.
 *
 * Only this package's own files are covered. The host application's routes and
 * bootstrap deliberately are not — they change with every release of the
 * product, and sealing them would mean a forgotten `license:reseal` after a
 * deploy takes a paying customer offline. Those are reported to the licence
 * server instead, where a change is visible without being fatal.
 */
final class Integrity
{
    private ?string $cached = null;

    private ?string $appDigestCache = null;

    public function __construct(private readonly string $root) {}

    /** Hex digest over every PHP file in the package, path and content. */
    public function digest(): string
    {
        if ($this->cached !== null) {
            return $this->cached;
        }

        $hashes = $this->fileHashes();

        if (isset($hashes['__unreadable__'])) {
            // An unreadable package directory is itself a reason to distrust
            // the installation, so it must not hash to the same thing twice.
            return $this->cached = 'unreadable';
        }

        if ($hashes === []) {
            return $this->cached = 'empty';
        }

        return $this->cached = hash('sha256', json_encode($hashes, JSON_THROW_ON_ERROR));
    }

    /**
     * Every PHP file in the package as relpath => sha256, sorted by path.
     *
     * The raw material for both the folded digest above and the vendor-signed
     * manifest the client verifies against. One walk, so the two can never
     * disagree about which files count.
     *
     * @return array<string, string>
     */
    public function fileHashes(): array
    {
        $hashes = [];

        try {
            $files = new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator($this->root, RecursiveDirectoryIterator::SKIP_DOTS)
            );

            /** @var SplFileInfo $file */
            foreach ($files as $file) {
                if (! $file->isFile() || $file->getExtension() !== 'php') {
                    continue;
                }

                $relative = ltrim(substr($file->getPathname(), strlen($this->root)), DIRECTORY_SEPARATOR);
                $hashes[$relative] = hash_file('sha256', $file->getPathname());
            }
        } catch (Throwable) {
            return ['__unreadable__' => '1'];
        }

        // Sorted so the result depends on the files, not on directory order.
        ksort($hashes);

        return $hashes;
    }

    /**
     * A digest of the host application's own source code.
     *
     * Only meaningful when strict mode is on. It covers every PHP, Blade and
     * config file the product ships, and deliberately excludes everything that
     * changes at runtime — storage/, bootstrap/cache/, .env, and vendor/ apart
     * from this package. Sealing those would turn ordinary operation (a written
     * log, a cache file, a session) into a licence violation, which is why
     * strict mode is off by default and needs a reseal after every deploy.
     */
    public function appDigest(string $basePath): string
    {
        if ($this->appDigestCache !== null) {
            return $this->appDigestCache;
        }

        $hashes = [];

        $excluded = [
            $basePath.'/storage',
            $basePath.'/bootstrap/cache',
            $basePath.'/vendor',
            $basePath.'/node_modules',
            $basePath.'/.git',
            // Built assets (Vite/Mix), the compiled bundle, uploads — all
            // regenerated by a build or written at runtime, none of it source.
            $basePath.'/public',
        ];

        try {
            $files = new \RecursiveIteratorIterator(
                new \RecursiveCallbackFilterIterator(
                    new RecursiveDirectoryIterator($basePath, RecursiveDirectoryIterator::SKIP_DOTS),
                    function ($current) use ($excluded): bool {
                        $path = $current->getPathname();
                        foreach ($excluded as $skip) {
                            if ($path === $skip || str_starts_with($path, $skip.DIRECTORY_SEPARATOR)) {
                                return false;
                            }
                        }

                        return true;
                    },
                )
            );

            /** @var SplFileInfo $file */
            foreach ($files as $file) {
                if (! $file->isFile()) {
                    continue;
                }

                $ext = strtolower($file->getExtension());

                // Code and configuration only. Not uploads, not compiled assets.
                if (! in_array($ext, ['php', 'blade.php', 'env', 'json'], true)
                    && ! str_ends_with($file->getFilename(), '.blade.php')) {
                    continue;
                }

                // .env itself is runtime configuration, never sealed.
                if ($file->getFilename() === '.env' || str_starts_with($file->getFilename(), '.env')) {
                    continue;
                }

                $relative = ltrim(substr($file->getPathname(), strlen($basePath)), DIRECTORY_SEPARATOR);
                $hashes[$relative] = hash_file('sha256', $file->getPathname());
            }
        } catch (Throwable) {
            return $this->appDigestCache = 'unreadable';
        }

        ksort($hashes);

        return $this->appDigestCache = hash('sha256', json_encode($hashes, JSON_THROW_ON_ERROR));
    }

    /**
     * A separate digest of the host application's licensing-adjacent files,
     * reported on each heartbeat so a change shows up on the dashboard.
     *
     * @return array<string, string>
     */
    public function hostFiles(string $basePath): array
    {
        $paths = array_merge(
            glob($basePath.'/routes/*.php') ?: [],
            [
                // Laravel 11+
                $basePath.'/bootstrap/app.php',
                $basePath.'/bootstrap/providers.php',
                // Laravel 10 equivalents
                $basePath.'/app/Http/Kernel.php',
                $basePath.'/config/app.php',
            ],
        );

        $hashes = [];

        foreach ($paths as $path) {
            if (is_readable($path)) {
                $hashes[basename(dirname($path)).'/'.basename($path)] = substr((string) hash_file('sha256', $path), 0, 16);
            }
        }

        return $hashes;
    }
}
